import type { Language } from "./run-result";

// Every interface string of the control room and the demo section, in
// each preset language. Topic names, titles and summaries are content and
// never come from here. A `Part[]` line interleaves text with config
// values ({ v }), which ConfigSpine renders as <ConfigValue>. `Text` is
// the English shape; `ru` must match it key for key (the type checks
// that; lib/control-room-text.test.ts checks it at runtime too).

export type Part = string | { v: string | number };

const en = {
  stages: {
    collect: "collect",
    window: "window",
    dedupe: "dedupe",
    cache: "cache",
    rank: "rank",
    cap: "cap",
    queue: "queue",
    review: "review",
    deliver: "deliver",
  },
  rail: {
    label: "Pipeline, last run",
    found: "found",
    drops: {
      undated: "undated",
      no_link: "no link",
      below_min_points: "below min points",
      outside_window: "too old",
      seen: "seen",
      dismissed: "dismissed",
      already_ranked: "cached below",
      off_topic: "off topic",
      over_max_items: "over cap",
      rejected: "rejected",
      expired: "expired",
    },
    below: (threshold: string) => `below ${threshold}`,
    threshold: "threshold",
    fullText: (n: number) => `+${n} full text`,
    thisRun: (n: number) => `+${n} this run`,
    never: "never",
    approvedOnly: "approved only",
    sent: (items: number, messages: number) => `${items} sent in ${messages} message${messages === 1 ? "" : "s"}`,
    shared: "shared feeds, before sorting",
    failed: (sources: string) => `failed: ${sources}`,
    reviewHint: (cadence: string) =>
      `approved items go out with the next digest; the agent picks up decisions at the start of its next run (${cadence})`,
    every: (hours: number) => `every ${hours} hours`,
    daily: "once a day",
  },
  topics: { label: "Topic", all: "all" },
  queue: {
    label: "Queue",
    statusLabel: "Status",
    statuses: { waiting: "waiting", approved: "approved", rejected: "rejected", all: "all" },
    unavailable: "queue unavailable",
    empty: "nothing here",
    approve: "approve",
    reject: "reject",
    undo: "undo",
    open: "open ↗",
    notWebLink: "not an http(s) link",
    invalidUrl: "invalid url",
    keysMove: "move",
    keysOpen: "open",
    reset: "reset",
  },
  configPane: {
    label: "Config",
    region: "Config and outcomes",
    fromRun: (hhmm: string) => `as of last run ${hhmm} utc`,
    hint: "a criteria change re-scores the topic",
    unavailable: "config unavailable",
  },
  spine: {
    label: "Config by stage",
    hnOn: (keywords: number, points: number): Part[] => ["hn: ", { v: keywords }, " title keywords, ≥", { v: points }, " points"],
    githubOn: (topics: number, stars: number): Part[] => ["github: ", { v: topics }, " topics, ≥", { v: stars }, "★"],
    rssOn: (feeds: number): Part[] => ["rss: ", { v: feeds }, " feeds"],
    hnSearch: (points: string): Part[] => ["hn title search, ≥", { v: points }, " points"],
    githubSearch: (stars: string): Part[] => ["github topic search, ≥", { v: stars }, "★"],
    perTopic: "per topic",
    presetFeeds: (feeds: number): Part[] => ["shared feeds: ", { v: feeds }, ", sorted into topics by the model"],
    hnKeywords: "hn keywords",
    githubTopics: "github topics",
    feeds: "feeds",
    fullText: "full text",
    window: (days: string): Part[] => ["published in the last ", { v: days }, " days"],
    dedupe: "already sent, queued, rejected or expired · the same url twice in a run",
    cache: "one verdict per url × topic",
    rubric: "rubric",
    cached: "cached",
    regrow: (gain: string): Part[] => ["re-score at ", { v: "2×" }, " and ", { v: `+${gain}` }, " points/stars"],
    noRegrow: "no re-score on growth",
    rank: (model: string, temperature: number, batch: number, prompt: number, pass: string): Part[] => [
      { v: model },
      " · temperature ",
      { v: temperature },
      " · batches of ",
      { v: batch },
      " · prompt v",
      { v: prompt },
      " · pass ≥",
      { v: pass },
    ],
    reader: "reader",
    criteria: "criteria",
    pickTopic: "pick a topic to see its include / exclude",
    cap: (perDay: string, windowHours: number): Part[] => [
      { v: perDay },
      " a day · rolling ",
      { v: `${windowHours}h` },
      " · the rest waits for a later run",
    ],
    queue: "held for your review",
    reviewInbox: (repo: string, days: number): Part[] => [
      "your decisions in ",
      { v: repo },
      " · undecided expire after ",
      { v: `${days}d` },
    ],
    reviewFile: (days: number): Part[] => ["the editor's decisions file · undecided expire after ", { v: `${days}d` }],
    deliverTelegram: (chat: string, hours: number): Part[] => [
      "approved only · telegram ",
      { v: chat },
      " · every ",
      { v: `${hours}h` },
    ],
    deliverFile: (title: string, hours: number): Part[] => ["approved only · digest ", { v: title }, " · every ", { v: `${hours}h` }],
    more: (n: number) => `+${n}`,
    less: "less",
    telegram: "telegram channels",
    telegramSoon: "coming soon — the engine doesn't read Telegram yet",
  },
  demo: {
    tag: (isoDate: string) => `demo · synthetic data · offline runs of ${isoDate}`,
    switcher: "Presets",
    tonyLive: "Tony live ↗",
    runs: "Run",
    run1: "run 1 — the queue fills",
    run2: "run 2 — decisions applied, digest sent",
    sandbox: "sandbox · nothing is saved",
    region: "Digest and config",
    digest: "Digest",
    digestPreview: "what the editor would receive",
    digestSent: "what the engine sent",
    digestEmpty: "approve items to build the digest",
  },
};

export type Text = typeof en;

const ru: Text = {
  stages: {
    collect: "сбор",
    window: "окно",
    dedupe: "дубли",
    cache: "кэш",
    rank: "оценка",
    cap: "лимит",
    queue: "очередь",
    review: "решения",
    deliver: "доставка",
  },
  rail: {
    label: "Конвейер, последний прогон",
    found: "найдено",
    drops: {
      undated: "без даты",
      no_link: "без ссылки",
      below_min_points: "мало очков",
      outside_window: "старые",
      seen: "уже были",
      dismissed: "отклонены ранее",
      already_ranked: "оценены ранее",
      off_topic: "не по темам",
      over_max_items: "сверх лимита",
      rejected: "отклонено",
      expired: "истекло",
    },
    below: (threshold: string) => `ниже ${threshold}`,
    threshold: "порога",
    fullText: (n: number) => `+${n} полный текст`,
    thisRun: (n: number) => `+${n} за прогон`,
    never: "никогда",
    approvedOnly: "только одобренное",
    sent: (items: number, messages: number) => `отправлено ${items} · сообщений: ${messages}`,
    shared: "общие ленты, до сортировки",
    failed: (sources: string) => `сбой: ${sources}`,
    reviewHint: (cadence: string) =>
      `одобренное уходит со следующей сводкой; агент читает решения в начале следующего прогона (${cadence})`,
    every: (hours: number) => `каждые ${hours} ч`,
    daily: "раз в день",
  },
  topics: { label: "Тема", all: "все" },
  queue: {
    label: "Очередь",
    statusLabel: "Статус",
    statuses: { waiting: "ждут", approved: "одобрено", rejected: "отклонено", all: "все" },
    unavailable: "очередь недоступна",
    empty: "пусто",
    approve: "одобрить",
    reject: "отклонить",
    undo: "отменить",
    open: "открыть ↗",
    notWebLink: "не http(s)-ссылка",
    invalidUrl: "неверный url",
    keysMove: "выбор",
    keysOpen: "открыть",
    reset: "сбросить",
  },
  configPane: {
    label: "Конфиг",
    region: "Конфиг и итоги",
    fromRun: (hhmm: string) => `по последнему прогону ${hhmm} utc`,
    hint: "смена критериев переоценивает тему",
    unavailable: "конфиг недоступен",
  },
  spine: {
    label: "Конфиг по стадиям",
    hnOn: (keywords: number, points: number): Part[] => ["hn: ", { v: keywords }, " слов в заголовке, ≥", { v: points }, " очков"],
    githubOn: (topics: number, stars: number): Part[] => ["github: ", { v: topics }, " тем, ≥", { v: stars }, "★"],
    rssOn: (feeds: number): Part[] => ["rss: ", { v: feeds }, " лент"],
    hnSearch: (points: string): Part[] => ["поиск hn по заголовкам, ≥", { v: points }, " очков"],
    githubSearch: (stars: string): Part[] => ["поиск github по темам, ≥", { v: stars }, "★"],
    perTopic: "по каждой теме",
    presetFeeds: (feeds: number): Part[] => ["общие ленты: ", { v: feeds }, ", по темам раскладывает модель"],
    hnKeywords: "слова hn",
    githubTopics: "темы github",
    feeds: "ленты",
    fullText: "полный текст",
    window: (days: string): Part[] => ["опубликовано за последние ", { v: days }, " дн."],
    dedupe: "уже отправлено, в очереди, отклонено или истекло · одна ссылка дважды за прогон",
    cache: "одна оценка на ссылку × тему",
    rubric: "рубрика",
    cached: "в кэше",
    regrow: (gain: string): Part[] => ["переоценка при ", { v: "2×" }, " и ", { v: `+${gain}` }, " очков/звёзд"],
    noRegrow: "без переоценки при росте",
    rank: (model: string, temperature: number, batch: number, prompt: number, pass: string): Part[] => [
      { v: model },
      " · температура ",
      { v: temperature },
      " · пачки по ",
      { v: batch },
      " · промпт v",
      { v: prompt },
      " · проходит ≥",
      { v: pass },
    ],
    reader: "читатель",
    criteria: "критерии",
    pickTopic: "выберите тему, чтобы увидеть include / exclude",
    cap: (perDay: string, windowHours: number): Part[] => [
      { v: perDay },
      " в день · окно ",
      { v: `${windowHours} ч` },
      " · остальное ждёт следующего прогона",
    ],
    queue: "ждёт решения редактора",
    reviewInbox: (repo: string, days: number): Part[] => [
      "ваши решения в ",
      { v: repo },
      " · без решения истекают через ",
      { v: `${days} дн.` },
    ],
    reviewFile: (days: number): Part[] => ["файл решений редактора · без решения истекают через ", { v: `${days} дн.` }],
    deliverTelegram: (chat: string, hours: number): Part[] => [
      "только одобренное · telegram ",
      { v: chat },
      " · каждые ",
      { v: `${hours} ч` },
    ],
    deliverFile: (title: string, hours: number): Part[] => [
      "только одобренное · сводка «",
      { v: title },
      "» · каждые ",
      { v: `${hours} ч` },
    ],
    more: (n: number) => `+${n}`,
    less: "свернуть",
    telegram: "telegram-каналы",
    telegramSoon: "скоро — движок пока не читает Telegram",
  },
  demo: {
    tag: (isoDate: string) =>
      `демо · синтетические данные · офлайн-прогоны ${isoDate.slice(8, 10)}.${isoDate.slice(5, 7)}.${isoDate.slice(0, 4)}`,
    switcher: "Пресеты",
    tonyLive: "Tony live ↗",
    runs: "Прогон",
    run1: "прогон 1 — очередь наполнилась",
    run2: "прогон 2 — решения применены, сводка ушла",
    sandbox: "песочница · ничего не сохраняется",
    region: "Сводка и конфиг",
    digest: "Сводка",
    digestPreview: "что уйдёт редактору",
    digestSent: "что отправил движок",
    digestEmpty: "одобрите материалы — здесь появится сводка",
  },
};

export const TEXT: Record<Language, Text> = { en, ru };
